### ISSUE TITLE
Service does not retrieve text near borders of the page.

### ISSUE THREAD

**Issue by AliNGatGeeks** [adobe/pdfservices-python-sdk-samples#13]
Hi 
I am feeding in pdf files for the text to be extracted. However, I am not getting some of the text back, when the text falls near the top and bottom of the page. 

![problem with text extract](https://user-images.githubusercontent.com/96764993/169083439-8a28de17-5ce9-4af5-a51e-3aebd9a1a660.png)

I also tried to add margins to the page by creating a new pdf with larger mediBox and merging the orignal file into it! it didnt work again!

any thing I can do to fixe this?

**Comment by paras-n** [comment]
Hi @AliNGatGeeks, issues raised here should address problems in the samples for this repo. Closing this ticket.

Adobe community forum will be the appropriate place for the same: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK.
