### ISSUE TITLE
ModuleNotFoundError: No module named 'adobe'

### ISSUE THREAD

**Issue by AbdulelahAlshehri** [adobe/pdfservices-python-sdk-samples#7]
I have been facing this issue despite installing all requirements (i.e, pip install pdfservices-sdk==1.0.2)
This message appears: 

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-aacff2934a59> in <module>
      3 import zipfile
      4 
----> 5 from adobe.pdfservices.operation.auth.credentials import Credentials
      6 from adobe.pdfservices.operation.exception.exceptions import ServiceApiException, ServiceUsageException, SdkException
      7 from adobe.pdfservices.operation.pdfops.options.extractpdf.extract_pdf_options import ExtractPDFOptions

ModuleNotFoundError: No module named 'adobe'
```
Thank you for your help in advance!

**Comment by Luci2015** [comment]
can you open CMD or Terminal and type:` pip freeze`
Do you see the pdfservices module listed there?
can you run` python --version` and check if you're running a version >= 3.6?
if all the above check out, can you run from terminal or CMD `python name_of_the_file.py` from inside the folder containing the script file you want to run, then confirm if you still get same error?

**Comment by paras-n** [comment]
Hi @AbdulelahAlshehri, issues raised here should address problems in the samples for this repo. Closing this ticket.

Adobe community forum will be the appropriate place for the same: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK.
